num = int(input("Digite um número: "))
num1 = num * 1
num2 = num * 2
num3 = num * 3
num4 = num * 4
num5 = num * 5
num6 = num * 6
num7 = num * 7
num8 = num * 8
num9 = num * 9
print("A tabuada é:")
print("{} x 1 = {}".format(num, num1))
print("{} x 2 = {}".format(num, num2))
print("{} x 3 = {}".format(num, num3))
print("{} x 4 = {}".format(num, num4))
print("{} x 5 = {}".format(num, num5))
print("{} x 6 = {}".format(num, num6))
print("{} x 7 = {}".format(num, num7))
print("{} x 8 = {}".format(num, num8))
print("{} x 9 = {}".format(num, num9))