name = str(input("Digite seu primeiro nome: "))
len(name)
name.count("o")
name.find("tavo")
new = name.replace("gustavo","casemiro")
print(new)
up = new.upper()
print(up)
down = up.lower()
print(down)
cap = down.capitalize()
print(cap)
stri = cap.strip()
divid = cap.split()
espace = "-".join(cap)