nome = str(input("Digite seu nome completo: "))
nome2 = nome.upper()
print("Seu nome completo em maiúsculas é:",nome2)
nome3 = nome.lower()
print("Seu nome completo em minúsculas é:",nome3)
nome4 = nome3.split()
nome5 = ''.join(nome4)
nome6 = len(nome5)
print("Seu nome possuí",nome6,"letras.")
nome7 = nome4[0]
nome8 = len(nome7)
print("O primeiro nome tem",nome8,"letras")